### ISSUE TITLE
pom.xml 配置问题

### ISSUE THREAD

**Issue by ImLeonLi** [PacktPublishing/Pentaho-8-Reporting-for-Java-Developers#2]
你好：

我们在使用这些范例时遇到 pom.xml 中的 repository 失效和dependency找不到的问题（可能其他章节的范例中也类似的问题）。
https://github.com/PacktPublishing/Pentaho-8-Reporting-for-Java-Developers/blob/master/Chapter14/interactive-report/pom.xml

# 问题1
下面这段配置的 http://repository.pentaho.org/artifactory/repo/ 已经失效，新的地址为 https://nexus.pentaho.org/content/groups/omni 。

``` xml
<repositories>
  <repository>
    <id>pentaho-releases</id>
    <url>http://repository.pentaho.org/artifactory/repo/</url>
  </repository>
</repositories>
```

# 问题2
下面的依赖已经在新的库中找不到了。
``` xml
<dependency>
  <groupId>pentaho-reporting-engine</groupId>
  <artifactId>pentaho-reporting-engine-classic-core</artifactId>
  <version>8.0-SNAPSHOT</version>
</dependency>
```

作者是不是可以更新下范例中 pom.xml 的内容。

下面是个好使的范例：
https://github.com/fcorti/pentaho-8-reporting-for-java-developers/blob/master/Chapter%2014%20-%20Building%20interactive%20reports/interactive-report/pom.xml

**Comment by fcorti** [comment]
Hello,

The url of Pentaho repository changes.
Below what you get when you try to open the URL into your browser.

![Screenshot 2019-07-25 at 09 16 53](https://user-images.githubusercontent.com/6010860/61853846-22f45280-aebd-11e9-820c-cafdae560889.png)

As you can read following the links, the suggestion is to replace the following tag

          <url>http://nexus.pentaho.org/content/groups/omni</url>
